### ISSUE TITLE
[Request] Option to open failed auto tag results in Quick Tag? Or at least push failed auto tags together at the bottom of the results list?

### ISSUE THREAD

**Issue by TheOnlyTick** [Marekkon5/onetagger#100]
Having to scroll through a large auto tag results list to find the various failed tags is a bit annoying, and there's no way to edit those specific files from the result list. Perhaps give an option to open those files in Quick Tag or Edit Tags?

**Comment by Marekkon5** [comment]
Hello, in the latest commit I've added this feature - after tagging you can just click open in QuickTag. This has been possible manually before as well, because all of the tagging results are saved as playlists too. 
Also in the results list, you can click on the matched/failed/skipped icons and it will filter the results.

You can get the binary from the Actions tab. Comment/reopen if you have any more issues. Thanks
