### ISSUE TITLE
[Suggestion] handle folder as release

### ISSUE THREAD

**Issue by ScrewedDriver** [Marekkon5/onetagger#116]
Pretty often the tracks from one release are mixed up with identical tracks released somewhere else.
It would  be very practical if there would be an option which allows to decide if files from a folder have to belong to one release.
An option "handle folder as release" would allow faster autotagging with better results.

**Comment by Marekkon5** [comment]
Hello, this feature has been requested earlier, however I am sorry, but won't implement it.
It is because of how 1T works - it searches multiple tracks at once - there is no relation or sharing data between individual track searches. They go in random order. Implementing this would significantly slow down the tagging process, and also would be technically very difficult to add and the overall impact would be rather very minimal.

**Comment by ScrewedDriver** [comment]
Thats really sad, when I use one tagger with a folder with 6 files its very common that one tagge recognize 4 of them correct. The rest is is not recognized or tagged with album information from a different release. So I'll need to do that manually. I'd love to see an option like "audio files in folder have to match the number of tracks in a release" - even if it would take a bit longer (and onetagger is freaking fast) but if it's not possible we ill need to do this manually.

**Comment by Marekkon5** [comment]
I do understand that it would be a good improvement, however it would require a huge refactor of core OneTagger components to implement it, and completely changing the way it internally works. So I might give it a shot in distant future, but not at the moment. Sorry and thank you for understanding.
