### ISSUE TITLE
Flac with title tags failed with error  "Shazam failed: Unrecognized format"

### ISSUE THREAD

**Issue by lord-carlos** [Marekkon5/onetagger#120]
I have a few flac files that I can't parse with forced shazam. It fails right away, no wait time.
"Shazam failed: Unrecognized format"

If I remove the title tag with mp3tag it works.

Version: Latest dev version from "actions"

https://drive.google.com/file/d/1njPwwMw7ql2-KcESo8G2q1OEPNNwrI7c/view?usp=sharing

**Comment by Marekkon5** [comment]
Hello, I've checked the file manually and the issue is within the Vorbis comment (tag) - it contains invalid characters (from ffprobe it seems that there is some `NITR` field that is the culprit). However since Vorbis is inside the FLAC file, the library tries to decode it and fails. Right now there is no other fix than manually removing that tag from the file. Sorry for the inconvenience.
