### ISSUE TITLE
1T doesn't fetch tags from Discogs

### ISSUE THREAD

**Issue by mtsbh** [Marekkon5/onetagger#147]
Hi, guys,
I'm having difficulties with Discogs. It was all good, but suddenly stopped working. I already tried and changed a couple of tokens, but It doesn't work. Can you, please, take a loot at it.
Thanks

**Comment by bascurtiz** [comment]
Correct, when I inspect the onetagger.log (click Settings in One Tagger > General > Open Data Folder):
`[ERROR] onetagger_platforms::discogs: Failed validating Discogs token: 403 Forbidden
 [WARN] onetagger_autotag: Failed creating AT source! Invalid Discogs token!`

There seems to be trouble on Discogs' side since yesterday:
https://www.discogs.com/forum/thread/971000

So nothing we can do about, until they fixed it.

**Comment by mtsbh** [comment]
I also have a problem with importing playlists into AutoTag. 

![image](https://user-images.githubusercontent.com/108582199/194165649-d87687a4-e447-414c-9aab-e8940415d3d2.png)

Should I open a new issue or no need?

[ERROR] onetagger::socket: Websocket: FromUtf8Error

**Comment by Marekkon5** [comment]
@mtsbh yes this is unrelated to this issue, please open a new issue and could you also send the m3u file that you're trying to import? Thank you.

**Comment by Marekkon5** [comment]
Discogs seems to be functioning normally now. Closing
