### ISSUE TITLE
iTunes downloads and embeds only 100x100 covers

### ISSUE THREAD

**Issue by trattaa** [Marekkon5/onetagger#149]
Good afternoon, if you use the Apple Music (iTunes) source as the source for the covers, then it only embeds 100x100.

Version 1.5.0, Windows 11

![2022-10-07_110905](https://user-images.githubusercontent.com/44088228/194505165-cafaa716-344c-47a3-a2ef-58b28e1041b8.jpg)

**Comment by bascurtiz** [comment]
Correct.
The free [iTunes API for developers](https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/iTuneSearchAPI/index.html) only supports up to 100x100px covers.

If you look up an example you will see there are 3 available resolutions, 30, 60 and 100px:
https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/iTuneSearchAPI/LookupExamples.html

In order to use the [Apple Music API for developers](https://developer.apple.com/documentation/applemusicapi/): 
_"To make requests to the Apple Music API, you need to authorize yourself as a trusted developer and member of the Apple Developer Program."_ 
...Meaning we have to pay 100 bucks a year. So that's a no-go with a free app like One Tagger.

If you want bigger covers, any other platform in One Tagger will do.

You could mix it up too.
If you're inclined to iTunes metadata, run 1T with iTunes selected the 1st time.
Then 2nd time, you choose other platforms and select Album cover only, with overwrite enabled.

**Comment by trattaa** [comment]
I see two solutions here.
The first solution: take a link to the cover from the API (for example, [here](https://is2-ssl.mzstatic.com/image/thumb/Features115/v4/f0/31/b2/f031b2b2-bcf0-6102-426f-e0b2c7437415/dj.vrgpwamf.jpg/300x300bb.webp)) and replace the url with the original cover (example [here](http://a1.mzstatic.com/us/r1000/063/Features115/v4/f0/31/b2/f031b2b2-bcf0-6102-426f-e0b2c7437415/dj.vrgpwamf.jpg)), uploaded to iTunes as is. That is, "*mzstatic.com/image/thumb/" is replaced with "a1.mzstatic.com/us/r1000/063/" and at the end, after expanding the picture (jpg /png), all information is deleted ("/100x100bb.jpg").
The second solution: there is another API, if you use [this ](https://tools.applemediaservices.com/apple-music)resource, you can catch a link like [this](https://tools.applemediaservices.com/api/apple-media/music/US/albums/528436018?l=en-US). I don't know the limits for her.

I don’t know, to make a separate Issue for this, but if you can make an implementation according to the solutions above, then you need to display the restrictions in the "Platform Specific Settings" on the resolution of the cover, sometimes there are covers higher than 5000x5000.

**Comment by Marekkon5** [comment]
ill check this bit later

**Comment by Marekkon5** [comment]
Hello, I've added a resolution slider in the latest commit (it changes the `100x100bb` part`), you can get the binary from the Actions tab to test it out. Feel free to comment or create an issue if you have any more problems. Thank you.
