### ISSUE TITLE
Quick Tag 10 UX Improvements

### ISSUE THREAD

**Issue by karass2** [Marekkon5/onetagger#165]
Hello!
Hello!

One Tagger is amazing as it is, but it could be better in terms of UX. Here are just a few things that I've noticed, while spending some time with it. I hope any of these are useful to other users as well and will see the light of the day in future releases.

1. I just want to listen to music in the background while working on something else, as playlist. I will get to a track and tag it if I notice something in it, or maybe skip a few tracks, while I'm busy with something else. In this case, it would be really useful if a next track would automatically start and a playlist just keeps playing. In case of multiple monitors, running it on a separate screen, makes it really handy.  This way tagging is not a task, but a passive thing..

2. I can't remove a tag from a track, if it was placed there by something else other then one tagger. I need to switch to Edit Tags, remove the tag that I don't want and get back to my list in Quick Tag. But this creates multiple issues, first I need to find a tag in Edit Tags, which is most likely sorted in a different way and then when I get back to Quick Tag, my scroll status is reset and I'm back at the top again, which means I need to scroll down and find the track I was working on. When you have 50+ tracks in the list. This becomes annoying really fast.

3. When you move the mouse over the waveform in the player at the bottom, the status of the waveform resets and it shows you where the track would skip if you click. At this time, you can't see where you are in a track anymore. It would be much better if instead there would be a red line for hover case that would show us where it would skip to, while the track status keeps moving as it was.

4. If you want to make any changes to title or artist information, you need to switch to Edit Tags (see issue 2 above). It would be really nice if we could click into the title and artist and edit the information right from this screen.

5. In my case, I tag a lot of similar tracks at the same time. That would be the same genre or style of music. Because of that, out of 50-100 tracks, same tags repeat as I do down the list. Some bulk functionality would be nice here to either select multiple tracks and assign tags that way to copy tags from one track and then simply paste everything to another and just add whatever is missing.

6. In other modules, I'm able to copy the folder path from windows into the field and the module automatically knows, which folder to work on. In this case, for some reason I'm forced with a dialog window to dig into my folder structure and find the right folder that way. The area in the top left, which shows the folder path could allow us to copy/paste a different path to it and switch to it on "enter" or "tab".

7. In order to remove a single tag from a track, I need to switch to that track, find the tag in the right panel and uncheck it. Wouldn't be faster if I could see a small X in any tag I hover on and be able to remove that tag just by click that X icon?

8. Track doesn't start playing, until the waveform loads completely. This takes just a second or two, but still is annoying.

9. The notification "Tags Saved!" appears over the waveform. If you move quickly while tagging, you're already on the next track, skipping and this notification is still there and you can't skip to the middle of the track as it's covering the waveform, making it unclickable. Top right corner of the screen would be an ideal place for this notification, next to the settings icon.

10. Some of the tracks are not playing and I get this error message. There is seems to be no issues with the file itself, as it plays fine in any other media player. I'm still able to tag the track in this case, I just need to hear the audio from another player.

![image](https://user-images.githubusercontent.com/46132879/206490798-88064d67-58a5-48c2-bfe9-c6c475d83e77.png)

Good Luck!

**Comment by Marekkon5** [comment]
Thanks for feedback! We'll review each point one-by-one and conclude what we will and wont add/fix asap with additional questions if needed. Thank you.

**Comment by dadarkman** [comment]
Hi,

I recently bumped into OneTagger and I'm so happy I did because it is by far the most advanced tagger I've come across. With that said, I feel that the UX and the multiple tabs can become confusing very quickly. @karass2 have mentioned quite a few of those in his thread. So, instead of opening a whole new thread, I'm piggybacking on this to add that OneTagger would benefit from having the traditional tagging view (i.e. MP3Tag, Tag&Rename, etc...); This is also a default view in Serato, Traktor, rekorbox)
![MP3-Tag-Traditional-View-Serato](https://user-images.githubusercontent.com/78093585/206811728-d3db286b-8485-4e6b-9eaa-545459b4832c.jpg)

DJs are so used to this view that it becomes so easy to navigate through huge lists of tracks faster than the view currently on the Quick Tag of OneTagger.

Thanks, and keep up the magnificent work on this app!

**Comment by Marekkon5** [comment]
Hello, 

@karass2
1. Added in latest commit - toggle is in settings.
2. I've made 2 changes related to this in the latest commit:
  a) Switching between QT and ET is ""seamless"" (if you select a track in QT, it should be opened in ET, and switching back to QT, should keep the last track)
  b) You can click the chips (custom values) and mood in the QT track to remove it.
  
  However there is currently no better way of editing any tag in QT, since QT was not designed to be general purpose tag editor, but rather for just adding those predefined values.
3. Added in latest commit, inspired by SoundCloud
4. See 2
5. QT was designed for single track editing, so this isn't currently possible and would require rewrite of QT. However if there is enough requests for it, we might add it in future.
6. Added in latest commit. 
7. Added in latest commit. You can use keybinds as well.
8. The waveform is loaded before the track, because otherwise Windows threw an error for having the same file opened twice. I need to do some testing to fix this issue.
9. Added in latest commit.
10. This is if your file isn't 100% correct and has some corrupted frames. Most players tend to just skip those, however in 1T I'd have to rewrite the audio decoding logic to do this. However I recommend using some app to fix your (corrupted) files.


@dadarkman 
QT wasn't designed for this kind of layout or bulk file editing. Doing something like this would require completely new section/redesign.

Thank you.

**Comment by karass2** [comment]
Thanks @Marekkon5 !

wow, I didn't expect you to react so quickly!

10. After I wrote that comment, I did a bit digging into the subject and found an mp3 fixer, it ran through my files and found a lot that were in need of tag location correction in file data. That must have been causing the errors. I haven't tried processing any of the clean files yet, but now my file prep process includes checking the files before tagging them :)

I agree with @dadarkman, if we had bulk editing with table view in one tagger, it would make life so much easier. ET module has a very good potential to become something like that. Although, it seems that, bulk tagging is somewhat of a ritual which everyone does differently and hence so many variations of these type of programs exist.

None of them are complete in my opinion, so we are all forced to use multiple apps to bring things into order. I am still amazed that none of the major DJ apps have implemented decent tag management functionality into their apps, for some reason I believe that it should have a huge impact of the amount of their users.

I've seen your "because we wanted to unify all the taggers" comment on other project, so maybe you're on the right track?? ;)

**Comment by dadarkman** [comment]
`QT wasn't designed for this kind of layout or bulk file editing. Doing something like this would require completely new section/redesign.`

@Marekkon5, 

Myself and three other DJ colleagues (which I put on OneTagger) used the program consistently for the last three weeks. Honestly, I wanted to see how they like it. Well, we all love and agree that the Auto Tag feature is currently KING in finding tags among all other tagging software we have gotten our hands on over the last 5+ years. I mean, it helped us fix so many files so fast! With all the praise for Auto Tag though, we wish we didn't have to switch to another program to edit files further manually.

So, some of the situation we feel that can/could be fixed/added in OneTagger:
1- Quick Tag: As much as you guys may not want to hear it, it's true: The Quick Tag and Edit Tags combo areas workflow is a drag. Instead of helping, they are slowing us down and becoming downright frustrating. After using them for that period, I can tell you that the slow process is caused by how the tag elements are laid out on the screen and how the program lacks batch/bulk editing entirely. I mean, I don't know anybody who would want to keep clicking one track after another and flipping through two panels to edit each single file. We tried it guys, it's NOT fun nor productive!

2- No way to re-arrange the tag fields layout on top. Also, visually, they are a bit confusing to look at because they are not correctly aligned to the content below them; After a while, it makes things feel disoriented.
![OneT-Not-Aligned](https://user-images.githubusercontent.com/78093585/209893506-a7a4907e-4336-408d-ad51-2448d7c94918.png)

3- The Year/Genre and BPM/Key stack combo style could be a one-liner.
 
Now, considering those three points and couple with the suggestion made in my previous comment above, once again we're kindly asking if you could at least consider adding an additional VIEW option where the elements are more linear looking.
See Mock-up:
![OneT-2](https://user-images.githubusercontent.com/78093585/209893771-5c241e82-2069-4e19-9542-171fd0d0da7d.png)

Think about it, with the current UI, OneTagger can only display 5 tags and a scroll is already needed to continue tagging. With a more linear, traditional VIEW, the screen could accommodate 15+ lines of tracks before a scroll is needed.

In the settings area, some improvement for faster workflow could also help us as users:
1- The Subgenre area input could use a setting arrangement like the Custom Note to add subgenre entries, that way we can just click an entry to delete or edit it instead of sniffing through the condensed line of texts to replace or fix errors.

_I read somewhere in a Reddit thread. I think it is in the 1.3.0 update thread; you answered a request by stating that you wouldn't implement it because so many other software already have it. Well, that hit me hard! The fact is, we are all scrubbing the bottom of the internet to find that one software that can get us all to the finish line. Trust me, given the option, we all would choose the one software that can help us as much as possible instead of having to switch through 4-5 applications for a couple of tasks.
So, I'd rather come back here and present to you as a user how awesome it would be to use OneTagger with those features included instead of having to combine and flipping between two or more other applications. Well, we (me and my colleagues) hope you consider._

Thanks, and happy holidays!

**Comment by Marekkon5** [comment]
Hello, thank you for the feedback. Since a bunch of people complained about QT only doing 1 track at once, I will probably have to rewrite it eventually. However it won't be quick. Thank you

**Comment by dadarkman** [comment]
` it won't be quick. `
Understood! We will be on the waiting end patiently.

Thank you.

**Comment by lord-carlos** [comment]
OP addressed many of my personal minor grievances. Nice to see how they get addressed so quickly <3

5. Same for me. Sometimes I download 10 new "groovy techno" tracks and want to tag them all the same. For this I sometimes still use mp3tag.
8. Yes, the loading and playing delay is somewhat annoying. Also skipping into a track is not instant. Makes it feel sluggish.

Being able to remove "old" tags is nice <3 Thank you.

**Comment by vvkanz** [comment]
As it was said earlier, it definitely needs a way to tag multiple selected files at once: add the same comment (I put source there vinyl/web), correct something in any of the tags for the whole release if there's a typo, etc.

**Comment by Marekkon5** [comment]
Multiple tags support should be available in latest commit / 1.7.0 future release. I'll also close this since inactive and too much has changed since then. Feel free to open new issues related to this.
