### ISSUE TITLE
Auto rename: Sanitize NUL byte in tags

### ISSUE THREAD

**Issue by martyn0ff** [Marekkon5/onetagger#168]
First of all, thanks for this wonderful tool. This is what I've been looking for a very long time, and I am very happy to have discovered it! 

I suspect that auto-tag feature sometimes produces tags that end up with NUL byte at the end. I don't think its an issue of auto-tag per se, but rather the music service it pulls tags from. That said, having NUL byte at the end of a tag makes it impossible to move files on Linux. In the example below NUL byte ends up in a tracknumber tag:

```
2022-12-18 13:17:29 [ERROR] onetagger_renamer: Failed copying /mnt/ssd/newdump/_TAGGED/00--yukari_okamura-step.mp3 -> "/mnt/ssd/newdump/_RENAMED/Oslated/VA-Oslated_5th_Anniversary_Compilation-(OSC004)-2021/05\0-yukari_okamura-step__original_mix.mp3": data provided contains a nul byte
```
A workaround for this issue is to apply `.replace("\\x00", "")` for corresponding tags But NUL byte ends up being inserted in different tags at times, so you have to apply it to each tag that is prone to this and rename pattern ends up bloated.

I cannot consistently reproduce this, as files end up with this issue seemingly without any obvious pattern. Nevertheless, I think it won't hurt to apply this sanitization regardless.

**Comment by Marekkon5** [comment]
Hello, the NULL bytes at end are caused because of some standards for some tag formats (mainly ID3), not by autotag directly.

However this issue has been already reported in #157 and fixed in https://github.com/Marekkon5/onetagger/commit/df07e5ea10c58fb7fe61384d5e4541939d5f85d6

It's not in a released version, however you can get the latest development/testing version from the Actions tab on Github. Let me know if it solves your issue. Thanks

**Comment by martyn0ff** [comment]
Thanks, this solves my issue.
