### ISSUE TITLE
Use `lofty-rs` for tag mapping?

### ISSUE THREAD

**Issue by uklotzde** [Marekkon5/onetagger#171]
I am currently investigating for myself if it is feasible to migrate to [`lofty-rs`](https://github.com/Serial-ATA/lofty-rs) for mapping between metadata and tags. I would be curious to hear your thoughts about this crate.

My motivation: Using a homegrown implementation based on low-level libraries like `id3`, `mp4ameta`, `metaflac` requires to deal with incompatibilities and interoperability issues and is tedious and not sustainable in the long term. I would prefer to join forces and contribute to a common, shared base.

**Comment by uklotzde** [comment]
See also: https://github.com/Serial-ATA/lofty-rs/issues/90

**Comment by Marekkon5** [comment]
Hello, the crate seems very promising, has nice examples and for such thing I'd definitely use this crate rather than custom solution. 
Also since it's open source, you can fork it or make PRs for any inconsistencies or non-standard behavior.

If you're suggesting it for 1T or comparing it to 1T implementation:
1. The code is kinda bad and unclean, I should rewrite it at one point. So I don't really recommend depending on it as a library.
2. 1T uses bunch of "abstractions" to make it more user friendly, which normal library wouldn't have. Like the iTunes or magic chatacter for mp4.


I hope this answer is sufficient for you / is what you've been asking for. Thank you
