### ISSUE TITLE
Fersh Install and beat port wont tag? 

### ISSUE THREAD

**Issue by Esenfur** [Marekkon5/onetagger#172]
"missing beatport config" ? 

https://i.imgur.com/NSII8wG.jpeg - How do i fix this, I've uninstalled and retried with same error. 
https://i.imgur.com/JbfgQRz.jpeg - the platform settings page is blank too.

**Comment by bascurtiz** [comment]
What OS are u using? macOS version or Windows version please.

Also, could you attach the log file of One Tagger here?

In order to find the log file, open One Tagger, click Settings icon > General > Open Data Folder.

Do like this:
https://youtu.be/RMxt0bom63k (Windows)
or
https://youtu.be/z9HbNycEbGM (macOS)

**Comment by Esenfur** [comment]
Windows 11. Latest build. 

Bizarrely it is working today! Good to close
