### ISSUE TITLE
Could you integrate other platforms such as SoundCloud, Deezer, Tidal, Qobuz, Amazon Music, Mixcloud or even Wikipedia ?

### ISSUE THREAD

**Issue by ripapi** [Marekkon5/onetagger#184]

**Comment by Marekkon5** [comment]
Hello, some platforms such as SoundCloud and Wikipedia have very poor metadata support or un-uniform one. So we won't be adding those. We will probably consider adding Deezer (since they have nice API), however most streaming services (Spotify/Tidal/Deezer/AmazonMusic) have almost the same song  availability, so I don't think it's useful to have them all.

**Comment by Marekkon5** [comment]
Added Deezer in latest commit. Closing as complete because of reasons above, feel free to comment/reopen if you have any objections or any more issues.
