### ISSUE TITLE
Getting 0 tags

### ISSUE THREAD

**Issue by TommyMcMusic** [Marekkon5/onetagger#194]
Not sure what is going on but now no matter how many or how few sources i use, i get 0 tags on unscanned mp3s

**Comment by Marekkon5** [comment]
Could you share the log? Settings > General > Open data folder.

**Comment by Marekkon5** [comment]
Hello, from the latest few sessions in the log:
- Most of the songs have a 1T tag, that they've been already tagged. You can disable the `Skip already tagged` tracks in Advanced settings. (NOTE: There was a bug that the option didn't show up, use the latest action build for it to show)
- BPMSupreme seems to be broken right now, will fix soon
- Shazam also had a bug, which is fixed in the latest Actions build.
- Some of your tracks are missing the title & artist tag (required to search for the track). If you do not have them, enable Shazam or Parse filename option.

**Comment by TommyMcMusic** [comment]
Fantastic thanks!
