### ISSUE TITLE
M4A BPM & KEY Tags Issue

### ISSUE THREAD

**Issue by KeelDev** [Marekkon5/onetagger#202]
Hi,

Have an issue where the BPM and Key was not being displayed for .m4a tracks. 

Looked further into this and it appears 1T looks at the com.apple.iTunes:KEY tag as oppose to com.apple.iTunes:initialkey tag which is the one all my files use. This field is written by Mixed In Key and used within Rekordbox, so can the option be provided to select which one is used?

With regards to the BPM, I am not sure why this is not displaying for M4A tracks. I expected Rekordbox to have written the BPM to the tmpo tag and this appears to be the case. I have a manual tagger application and this displays the BPM for M4A files, I am under the impression the manual tagging application automatically looks to the tmpo tag for the BPM field when using MPA files.

Looking at the code for 1T, it appears 1T should also be looking at the tmpo tag? So why is this not working/displaying the BPM within Quick Tag?

Hopefully you can help, thank you

**Comment by Marekkon5** [comment]
Hello, 

1. Changed the MP4 KEY to initialkey, because after googling it seems the `KEY` version isn't used anywhere and probably was based on our assumption, meanwhile the `initialkey` one returns a bunch of results and is used in software like Picard.

2. 1T does use `tmpo` tag, however it tries to parse the number as an integer (in QT). Perhaps your files have decimals in BPM or some trailing/leading spaces. Could you perhaps provide the file? Thank you.

**Comment by KeelDev** [comment]
[Benny Blanco, Halsey, Khalid - Eastside.m4a.zip](https://github.com/Marekkon5/onetagger/files/11011466/Benny.Blanco.Halsey.Khalid.-.Eastside.m4a.zip)

**Comment by KeelDev** [comment]
My manual tagger is able to pull the BPM from that file but when I look at the meta matrix it states Rekordbox cannot write the tmpo tag? So how is my manual tagger able to fetch the BPM from that file but 1T cannot display the BPM? Hopefully that makes sense.

**Comment by Marekkon5** [comment]
Found the bug, fixed in latest commit. You can get the latest binary from the Actions tab to test it out. Feel free to comment or reopen the issue if you have any more problems.
