### ISSUE TITLE
Feature: Tagging support for .WAV files 

### ISSUE THREAD

**Issue by SteamWo1f** [Marekkon5/onetagger#207]
#### That is why I am asking for support for .WAV files

**Comment by Marekkon5** [comment]
Hello,

By definition WAV files shouldn't support metadata, and you should use formats like FLAC which are lossless and support metadata and other features as well.

However because people opened too many issues on this topic, we already added WAV (ID3). You can get the beta/unreleased binary from the Actions tab to test it out.

Thank you.

**Comment by SteamWo1f** [comment]
Thank you very much.
