### ISSUE TITLE
Docker ?

### ISSUE THREAD

**Issue by flovanc** [Marekkon5/onetagger#25]
simple question here, is a port to Docker possible? This in order to be able to use Onetagger on for example a dedicated server ...

**Comment by Marekkon5** [comment]
You can compile and run it inside docker, however I don't really recommend that as it's designed to be ran locally, so there are probably some security flaws. Also some parts like player won't work (because they are server-side). I will add expose argument soon to enable running it headlessly, however now you need to modify code to be able to run it outside of localhost.

**Comment by Marekkon5** [comment]
You can now use the `--expose` (and `--server`) flags which will make 1T use `0.0.0.0` as host, so you can run and control it remotely. You can get the latest binary from Actions tab.
