### ISSUE TITLE
Feature request: Auto Rename Parent Folder Variable (ex: %parentfolder%)

### ISSUE THREAD

**Issue by Grenoybel** [Marekkon5/onetagger#253]
Awesome software, If you have the opportunity to do something like this, it would be great, cheers.

**Comment by Marekkon5** [comment]
Hello, added in latest commit.

`%path%` - path of file, 
`%abspath%` - absolute path (for example: `C:/Users/a/Music/test.mp3`)

Added also functions `.parent()` and `.filename()`

So `%abspath.parent().filename()%` is essentially the parent folder name. `%abspath.parent().parent().parent().filename()%` is just name of the parent of parent of parent folder. Just `%abspath.parent()%` without the `.filename()` will return the whole path instead of just the folder name.


You can get the binary from the Actions tab to test it. Feel free to comment or reopen if you have more issues. Thanks
