### ISSUE TITLE
feature request: also show release date and label/publiusher in manual tag window

### ISSUE THREAD

**Issue by derzw3rg** [Marekkon5/onetagger#266]
maybe in the same line as Album: ALBUM, Genres: GENRE, BPM: BPM

**Comment by Marekkon5** [comment]
How manual tagger works is: 
1. It fetches minimal metadata (ie. what's available on the results list) 
2. Once user selects the track, it will fetch all the other info while it's applying.

Because of that there is no label, publisher, release date or other stuff available for most platform in the search results and adding it would cause very long load times. So therefore won't be implemented.
