### ISSUE TITLE
OneTagger - Catalog Number

### ISSUE THREAD

**Issue by DrTekkno** [Marekkon5/onetagger#27]
hi,

when i get the tags from beatport it grab the catalog number but it display it only in OneTagger when i use for example Tag & Rename the catalog tag is empty.

your software is a very good alternative to beatport pro. Great Work.

![Capture d’écran 2021-08-01 à 21 50 19](https://user-images.githubusercontent.com/88290189/127784034-c2deeb1a-a8d8-4a65-bf00-39e01b400670.png)

**Comment by Marekkon5** [comment]
The tag editor you're using is probably looking for the Catalog Number in different tag. Do you know which? Or what is the full name of the tag editor software? Thank you.

**Comment by Marekkon5** [comment]
So @bascurtiz did the research and Tag & Rename writes catalog number to comment field with "Catalog Number" description, which is case sensitive. This is super rare and unstandardized so 1T won't support it, and most apps dont either. You have to manually copy the tag in 1T Tag Editor. MP3Tag and such programs don't work either because they are case insensitive. This is more of a Tag & Rename issue, you should contact their support. Thank you.
