### ISSUE TITLE
Many files open errors

### ISSUE THREAD

**Issue by smokingbehind** [Marekkon5/onetagger#277]
When using Quick tag section, many mp3 files do not open with errors like this (check screenshot)

<img width="406" alt="2023-09-09 в 20 41 37" src="https://github.com/Marekkon5/onetagger/assets/34321240/ebaaff38-3e26-46c5-a710-c36b418a5aa7">

<img width="643" alt="2023-09-10 в 10 40 15" src="https://github.com/Marekkon5/onetagger/assets/34321240/2ce5f27a-36c0-4cf5-8434-591162451641">

file:
https://drive.google.com/file/d/1C6c51QxJ8w16_zfzYtQB8NfauLo4VvHb/view?usp=sharing

**Comment by Marekkon5** [comment]
Hello, in this case your file contains invalid frames (it is slightly corrupted or not up to spec). Most players can still play it because they skip those frames, however 1T won't play it, because technically your file is corrupted. There are some programs to fix it.
Also this only affects the player, so if you want to edit the tags, you can ignore this. 
Thank you.

**Comment by bascurtiz** [comment]
Issue according to [AudioTester](http://www.vuplayer.com/files/audiotester.zip):
![image](https://github.com/Marekkon5/onetagger/assets/34075088/514212af-da2b-480a-b011-f5907849cad0)

To fix this, use [foobar2000](https://www.foobar2000.org/download), like this:
![image](https://github.com/Marekkon5/onetagger/assets/34075088/d4639c10-05df-4d4f-aad4-495be9c86dfe)

Now the file is fixed and playable in 1T:
![image](https://github.com/Marekkon5/onetagger/assets/34075088/6b31935f-c2ab-431c-9107-53ed3bd57da7)
