### ISSUE TITLE
MusicBrainz Correct Tagging

### ISSUE THREAD

**Issue by DizziDee704** [Marekkon5/onetagger#291]
I have been using the program to tag against MusicBrainz.  It does a great job except it uses the character (,) comma instead of the words or characters “feat., ft. or & in the title of an artist.  How can I get an exact match against MusicBrainz?

Example: Janet Jackson, Michael Jackson 
instead of 
Janet Jackson Feat. Michael Jackson.

**Comment by Marekkon5** [comment]
Hello, the artist field never has the words `feat.` or `ft`. Those are usually in the title only (and that's kinda improper). OneTagger fetches raw data from MusicBrainz and saves them into proper tags. 
The official MusicBrainz website does use `&`, but that's just a separator for the user. If you do wish to have `&`, you can change the value separator in the advanced tab (not recommended, because some players treat that as single artist with `&` character in their name).

![image](https://github.com/Marekkon5/onetagger/assets/15169286/1439d84b-8223-48e2-9a19-a67607271087)

If you have more questions / problems, feel free to comment or open new issue. Thanks
