### ISSUE TITLE
How to generate python bindings

### ISSUE THREAD

**Issue by tha23rd** [Marekkon5/onetagger#296]
I noticed that there are a couple of python related crates. Does this repo have a built in mechanism to generate python bindings?

Thanks!

**Comment by Marekkon5** [comment]
Sorry, I forgot to update the README on how to build. You can reffer to the CI scripts (.github/workflows/build.yml) for instructions.

**Comment by tha23rd** [comment]
> Sorry, I forgot to update the README on how to build. You can reffer to the CI scripts (.github/workflows/build.yml) for instructions.

No problem! I did try following them, but get a segmentation fault whenever I try to import the `onetagger` library. Just confirming that importing the onetagger library into other Python apps works for you?

**Comment by Marekkon5** [comment]
It does work for me. However the `onetagger` library is only available to scripts ran thru the OneTagger Python. Are you trying to make a custom platform and test within 1T or trying to externally import it? Thanks

**Comment by tha23rd** [comment]
>>>  trying to externally import it
Exactly this - I'm building a project (in python) and was trying to see if I could leverage some of the code in this project through python bindings

**Comment by Marekkon5** [comment]
Sadly OneTagger doesn't support this and is not intended for it. The Python integration is supposed to be as a "plugin" system for 1T, rather than 1T being a Python module/library. 

I might actually make onetagger a Python module (in future) to make testing custom platforms easier, however it won't be intended to be used as standalone library.

I'll close this issue now, because of the reasons I said above, however feel free to comment or open new issues if you have any questions / problems and I'll try to reply if I can. Thanks
