### ISSUE TITLE
[Feature Request] Add "Mixed Case" function to capitalize the 1st letter of each word of a string

### ISSUE THREAD

**Issue by SP-937-215** [Marekkon5/onetagger#318]
Hi there!

Great piece of software, nice technology stack... congratulations !

See below a feature I think could be useful. Thanks!

Add "Mixed Case" function to capitalize the 1st letter of each word.

The behavior could be as follow:

Template: %artist.mixedcase()%
Input: ralphie b
Output: Ralphie B

**Comment by Marekkon5** [comment]
Hello, added in latest commit. However I've named it `titlecase` since I've seen it called that way. Usage is same as your example. You can get the build from Actions tab to test it out.
Also thank you so much for the sponsor!

Feel free to comment or open new issue if you have more problems/requests. Thanks
