### ISSUE TITLE
Suggestion: "Sort by"

### ISSUE THREAD

**Issue by minecreeper313** [Marekkon5/onetagger#325]
First of all, amazing software. I'm surprised I didn't know about this earlier.
I would like to suggest the addition of a **"Sort by"** button or dropdown menu in the _Quick Tag_ section.
I've recently been adding new moods and tags, but end up dragging each value to the desired spot; which gets tedious after a while.
I did notice a **"Sort Values"** button in the far-right column, but it doesn't seem to do anything. _Maybe I'm missing something._

What I'd really like is, even just in the settings, a **"Sort in Alphabetical Order"** and **"Sort by Color"** option.
This way, the user can add new values and then click the button to either _sort everything in alphabetical order_ or, **exclusively for Moods,** _sorting them by color_ to have a nice **rainbow gradient** spanning across the bottom section.
This way every value can be identified and better found by following the alphabet, and if preferred the moods can be looked at by Color.

**Bonus suggestion:** change the Album Art in the Edit Tags section to be **a simple drag and drop** _with a dropdown on the side that defines what type of album art it is._ It's nicer if the user doesn't have to click so many times to get an album art going. And it sucks to have to remove the image and re-do the process if you choose the wrong type or change your mind later.

**Take a look at Mp3Tag for more inspiration.** The UI in that software is just _a tad bit more user friendly and intuitive._ I still find myself using that more than OneTagger to edit tags. And it would be great to do everything in one application.

Keep up the great work. I am loving this software.

**Comment by Marekkon5** [comment]
Hello, in the latest commit (you can get the build from Actions tab to test it out) I've added sorting alphabetically for QT Custom, moods & genres. I won't add sorting by color because it's kinda very complicated, because the actual colors aren't stored, but rather the names / css classes. 
As for the existing "Sort by" button, it is a relic of the past which actually reorders the values inside the tag according to the ordering in QT. 

Edit Tags: You can also now drag a new picture on top of the old one to replace it.

Feel free to comment or open new issues if you have more requests / problems. Thanks
