### ISSUE TITLE
Shazam

### ISSUE THREAD

**Issue by alskop** [Marekkon5/onetagger#326]
Anyone else having trouble getting "unexpected end of file" and other "unexpected" error messages with Shazam functionality on Windows v1.7? I am new to this program, so perhaps it's "user error..."

**Comment by Marekkon5** [comment]
Hello, sometimes those unexpected end of file are caused by corrupted or non standard files. Can you send us the log so we can see more details? (Settings > Advanced > Open data folder > onetagger.log).

Also you can try the latest development version from Actions tab which sometimes has fixes for some of those problems.

Thanks

**Comment by markosopcic** [comment]
I'm getting a similar problem, I'm on MacOS and Linux, and i get the following error on both platforms:

`Shazam failed: reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) }`

Could it be that the Shazam API stopped working? Because it used to work a month ago and I haven't changed anything.

**Comment by Marekkon5** [comment]
Hello, I've just tested it and shazam works for me. Could you please provide song title & artist so I can try to reproduce? Or can you try the latest Actions build? Thanks

**Comment by markosopcic** [comment]
Hmmm it seems to be working now, at least for me... MIght've really been a Shazam API issue. 
Maybe OP still has the issue.

**Comment by markosopcic** [comment]
And now it's happening again. Not really sure how to explain it. 
<img width="643" alt="image" src="https://github.com/Marekkon5/onetagger/assets/32719316/be1d2206-f4c6-45c6-b5a6-0eb5cf0af47e">
Here's my log file as well:
[onetagger.log](https://github.com/Marekkon5/onetagger/files/14108737/onetagger.log)

**Comment by Marekkon5** [comment]
It works for me, so I am assuming it's some kind of rate limit, or blocking or other reason. In the latest commit I've added more debugging info regarding this, so if you could try the latest Actions build and send us the log again it would be great. Thanks

**Comment by markosopcic** [comment]
Looks like Shazam is rate limiting, yes 🤔 
[onetagger.log](https://github.com/Marekkon5/onetagger/files/14110410/onetagger.log)

**Comment by alskop** [comment]
It would seem it's working now, awesome. Wondering, again as a new user, is there any way/setting to prefer tagging the song with the ORIGINAL album a song came from as opposed to "Greatest Hits" or random box sets? Seems to be little consistency in that regard. Otherwise great product!

**Comment by Marekkon5** [comment]
There is an option to prefer oldest releases, however OneTagger cannot really distinguish those at the moment and takes the best match which the site returns. You can try manual tagger if it's a big problem.
