### ISSUE TITLE
Not responding

### ISSUE THREAD

**Issue by nikolaiyago** [Marekkon5/onetagger#352]
Hello, i have tried all the features several times. and tried several combinations. i also found out that there was no back to default mode and. and when i try do delete the app or reinstall it everything is just like i left it. thats nice for some. But in this case i am not able to use the progarm anymore. its not repsonding and i can not reset it. it just freezes and i looks like its going to do somthing but dosent do anything for 45 min. 
is there any reason why it would not repsond and just freezes. do i need to fix the setting? 
plis help.
Love the program btw.

**Comment by nikolaiyago** [comment]
i noticed it only happens when i select spotify. and there are problesm even tho i register a new spotify deleveloper mode

**Comment by Marekkon5** [comment]
Hello, there has been some issues related to this, and basically Spotify started being aggressive with their rate limits, and some people reporting that they got as high as 24-hour rate limits. You can check the log which should say the exact time. There isn't much 1T can do to prevent this (rate limit delays are dictated by Spotify). 

In latest commit I've added an artificial delay, and erroring on too high limits,  so maybe it will help, but I will close this for now since this is Spotify-side issue, and we can't do anything (unless maybe slowing down more).
You can get the binary from the Actions tab. Feel free to comment or open new issues if you have more problems.

Thanks
