### ISSUE TITLE
Auto Tag - Little to no feedback for error states

### ISSUE THREAD

**Issue by Asanche** [Marekkon5/onetagger#398]
Let me describe a few scenarios I have run into this:

1. loading a library in Documents when the app does not have permissions. It will just say it has 0 files to process with no dialog, popup, toast, or messaging of any kind that there was any sort of problem. It just looks broken...
2. This one is a bit more complicated. I prefer Spotify's tags. They tend to be multi-genre, are uniform, and actually have DnB subgenres unlike beatport. I randomly hit a point where it stopped processing. The app just sits there doing nothing on the processing page at 0/~1200. All I want to do is reprocess some files. There is no indication of the response code from the spotify API, if that is the problem, or if there is some other problem.

So, as a meta question:
- Is there a developer console somewhere I can read, or is there a log file I can look at somewhere? This software is super handy when it works but a completely obtuse black box when it is not. Ofc I could pull the code and compile it, but I have not dipped my toe into rust as of yet.

**Comment by Asanche** [comment]
I see there is a log file under Settings -> General -> Open Data Folder

I can definitely see that it is a spotify rate limit thing based on the logs.

That being said, their docs say it is on a per-30 second basis, but it appears maybe there is more to it than that? Is there some max API query limit using a developer app that I am hitting? I mean pulling a genre can't be that expensive on their end...

**Comment by Marekkon5** [comment]
The app has no concept of permissions, it is a desktop app, therefore it's up to user to allow it. However there is a log, where you can see the detailed info on errors. You can find it in Settings -> Advanced -> Open data folder. Also tagging errors can be seen when hovering over the error icon.

Same applies to 2. 1T doesn't stop mid way, it has to finish the currently processed track. So most likely you've hit a rate limit so it seems like nothing is happening. You can check the log to see. In either way it is safe to close the app to "cancel".


To the new comment: try the latest Actions build, it has some fixes related to rate limits. "Very high" rate limits are usually because of Spotify, not 1T (like Spotify provides the time limit to wait). You could also try using it with just 1 concurrent search, or creating another app in Spotify Developer account dashboard.

**Comment by Asanche** [comment]
Yeah, I'm seeing a very specific sleep that is on the order of like 6 hours, so I was beginning to assume that spotify has some very specific annoying rules for hitting their API.

Thank you for the speedy response.

I guess I assumed even if you have no concept of permissions, you would receive a catchable exception when you lack the required permissions, no?

**Comment by Marekkon5** [comment]
Well on paper yes, errors when loading files should be caught and that includes permission errors. However permissions are implemented differently on different OSes (or even enviromnents), so that might be the cause why 1T might not catch that.

**Comment by Asanche** [comment]
Gotcha, I am on a 2017 macbook pro for my DJ machine, so it is at least a major OS update behind. That may explain some of the weirdness lol.

**Comment by Asanche** [comment]
Anyways, feel free to close this, and thank you for the help :D

**Comment by Marekkon5** [comment]
No problem, since I never used a Mac, I don't notice those problems specifically, and there weren't any open issues about it beforehand.

**Comment by Gregoor** [comment]
just ran into this as well!
