### ISSUE TITLE
NEW Idea for identified tagging

### ISSUE THREAD

**Issue by Nickyg001** [Marekkon5/onetagger#409]
Considering that it is possible to cascade down various platforms from which to draw the metadata and if it doesn't find them in one it searches for them in another platform, and considering that for example at least on the Genre the various platforms report different data, would it be possible to insert an icon next to the file data so as to understand which online platform the downloaded metatags come from (beatport, traxsource, spotify, Deezer, etc.)?

![image](https://github.com/user-attachments/assets/03459757-c5c7-4f03-812e-056a3b390b7b)

**Comment by Marekkon5** [comment]
OneTagger does not have any internal database, and does not store which platform was the track tagged at in the metadata. Furthermore since it can be tagged on multiple sources at once it can be invalid / wrong. Also we don't really see any use case for this here? QuickTag is __kind of__ unrelated to AT, like QuickTag is when you want to manually change metadata, not for checking what AT did. 

So sorry, won't be added, I hope the explanations make sense.
