### ISSUE TITLE
Streaming tracks taging

### ISSUE THREAD

**Issue by kasper77pl** [Marekkon5/onetagger#424]
Hello Guys

Thank you for the app. It is really helpful for djs !

Is there a chance to add possibility to implement taging (mostly AutoTag & Audiofeatures) by Onetagger also for streaming tracks (for instance tidal) in DJs program like Virtual DJ, Serato & so on? 

VirtualDJ now use discogs for autotaging but only for some tags. Your app is much better when it comes to AutoTaging & Autofeatures. 

I know it can be some challenge because it would need to integrate with DJs program databases but maybe you can think about that? ;)

Thanks in advance for the review !

**Comment by Marekkon5** [comment]
Hello, similar question was asked here before, however 1T is focused on tagging files rather than database. Tagging a database is extremely expensive (time-wise), since we would have to (in most cases reverse engineer) the database formats of all DJ apps, implement readers & writers for them, decode the structure / layout / data format, and maintain it in case of updates (since those aren't supposed to be exposed, the app authors can change them however they want). 
So sorry we won't be supporting writing to DJ databases directly. I hope the explaination is enough. Feel free to open new issue if you have more problems/requests/questions.

**Comment by kasper77pl** [comment]
I see. Thanks for the response !

**Comment by kasper77pl** [comment]
Maybe one more thing ;) 

There is an app developed by ATGR https://www.atgr.nl/ called DJ Conversion Utility Streaming (DJCU/s)
https://atgr-production-team.sellfy.store/p/dj-conversion-utility-streaming-djcu-s-for-macos/

I fully understand you don't want to maintain interfaces to dj program's databases so in that case maybe you could think about integration with DJCU/s? They maintaing interfaces to all DJs program. This would be great synergy ;)

Best regards !
