### ISSUE TITLE
Feature Requests: Spotify Genres and Selecting Multiple Genres

### ISSUE THREAD

**Issue by buges** [Marekkon5/onetagger#64]
Hi

A request please for getting spotify's genres for a track when auto tagging, and the ability to select multiple genres from the
bottom list in quick tag.

Thanks

**Comment by Marekkon5** [comment]
1. Spotify genres - I've just added it in the latest commit (you can get the binary in the `Actions` tab). The reason we decided to not to include it at first is, because Spotify only has genres for artists, not individual tracks. So all tracks from the same artist will have the same genres. We will add warning there as well.
2. Quick Tag - it was a decision we made some time ago, to make genres (and moods) single value only. So I will not change it at this moment. However - custom tags can have multiple values, and can write to the genre field (ID3: `TCON`, FLAC: `GENRE`, MP4: `©gen`). So you can use that.

**Comment by Marekkon5** [comment]
Since a bunch of people requested it - I added multiple genres. You can get the latest binary from the `Actions` tab to try it out.
