### ISSUE TITLE
Suggestions for use with iTunes/Music Libraries

### ISSUE THREAD

**Issue by djtechonline** [Marekkon5/onetagger#68]
This app has lots of potential but there are a few things that, as a DJ who uses Apple's Music App (formerly iTunes) to manage a large music library of 60,000+ tracks on my Mac, I think would be EXTREMELY helpful if these features could be added:

1.) Ability to drag & drop tracks from iTunes/Music for auto tag
2.) Option to retrieve Metadata from iTunes Store for matched AAC files
3.) Higher resolution for embedded images.  At least 500x500 pixels if not double that

As it is now, I am very impressed but I find tagging files in my library very difficult - especially in having to select folder paths.  Keep up the good work.  You certainly have something here!

**Comment by Marekkon5** [comment]
1. OneTagger is designed to tag whole folders, rather than individual songs, so I won't really add that. + Drag & Drop requires platform specific implementations, and I don't have a Mac so I can't really do that either. However you can export your tracks which you wanna tag as playlist and drag and drop it there. 
2. There already is iTunes option in the autotagger. AAC is supported as well.
3. It's a limitation of the iTunes API. You can use any other platform (Beatport, Traxsource, Spotify....), because they have high resolution art.

Yes I do understand that, however you can just select the parent folder and it will tag all the child folders (and child folders of those) if you wanna tag your entire library. Also you can just export as m3u in iTunes and use that instead of path. Thanks

**Comment by Harmonizer-byte** [comment]
I also think that you need to add the option to edit individual tags in separate files.  And I am missing a normal browser on the left side.  I want to have a complete user experience in one program, and not just a part of some separate functions.  If this program is for working with tags, then I would like to see full functionality, like in aytyuns or a musical bee, but with additional functions that one tagger has.  I mean, my logic regarding the choice of my main program for managing the library is that the more processes I can do in complex in one program, the more value it brings to me.

**Comment by nico-ottati** [comment]
Hi. I'm a DJ and use iTunes as well, mainly because of the Smart Playlists. I then use Traktor for playing.
I have another suggestion that maybe you guys can work out, and is that It would be amazing if you could solve the ratings issue. I'm currently tagging all the tracks, adding them into iTunes, and then manually re-rating the tracks as I already did in Onetagger, because of ratings won't update into iTunes.
I'm not a developer, so I don't know if this is possible, but if you actually can, I think it would be an amazing feature.

**Comment by bascurtiz** [comment]
@nico-ottati 
Star rating in iTunes isn't tag-based. So when you tag a song in iTunes, it writes this value to its internal database. 
Not to the file (or tag) itself. 
iTunes refuses to read the rating tag when filled in by One Tagger, Mp3tag, MusicBee, etc. cause it simply doesn't support it.
So not much we can do.

FYI: Traktor Pro 3.4 [supports smart playlists](https://www.digitaldjtips.com/2020/08/smart-playlists-smartlists-traktor-pro/) nowadays.
