### ISSUE TITLE
Genres get cut off if there's too many to fit on screen

### ISSUE THREAD

**Issue by rshea0** [Marekkon5/onetagger#75]
When there's too many genres to fit on screen, they just overflow and you can't select all of them.

Genres should wrap to multiple lines if they overflow.

**Comment by SunwalkerDJ** [comment]
Nice idea! We need more genres
I have briefly drawn 2 variants for how this can be implemented using the appearance of canvases on mouse hover:
![1](https://user-images.githubusercontent.com/96825311/149231616-4d84fe0f-8ecc-47fe-a0b6-ea984e803cb5.png)

I like the second option more, because it is more variable:
![2](https://user-images.githubusercontent.com/96825311/149231628-a3593d64-e0f8-44b8-a0da-6ca6d3b8dedc.png)

**Comment by bascurtiz** [comment]
@rshea0 
Yep. We are aware of there's too little space for Genres , though depending on your resolution.
What's your resolution btw?

@SunwalkerDJ 
Cool mockups!
We like to keep the lowest resolution of 1280x720 in check, so keep that in mind when making future mockups please =)

(I think it was you and) some other people who requested the browser on the left, cause it's convenience (basically any DJ app does it like that).

So without further adue, this is the mockup we would like to introduce and create.

![image](https://user-images.githubusercontent.com/34075088/149234039-5d58e6f2-1e4d-4609-98d1-0c7cb62cad03.png)

1. moods on top (full row / sticky)
2. folder + filter browser on the left
3. search bar dense + icon instead of text
4. genre + sub genre bar (preferably when hovering over the main genre, the sub genre bar appears, to click on such subgenre)
5. custom tag sections collapse/expandle (to make room when u have large lists in multiple sections)
6. adding using + icon / enabling using checkbox (to make it more user-friendly to add/remove/change tag name)
7. when hovering over such tag, x icon appears to delete.

This way we solve most problems.
What you guys think?

**Comment by SunwalkerDJ** [comment]
> @rshea0 Yep. We are aware of there's too little space for Genres , though depending on your resolution. What's your resolution btw?
> 
> @SunwalkerDJ Cool mockups! We like to keep the lowest resolution of 1280x720 in check, so keep that in mind when making future mockups please =)
> 
> (I think it was you and) some other people who requested the browser on the left, cause it's convenience (basically any DJ app does it like that).
> 
> So without further adue, this is the mockup we would like to introduce and create.
> 
> ![image](https://user-images.githubusercontent.com/34075088/149234039-5d58e6f2-1e4d-4609-98d1-0c7cb62cad03.png)
> 
> 1. moods on top (full row / sticky)
> 2. folder + filter browser on the left
> 3. search bar dense + icon instead of text
> 4. genre + sub genre bar (preferably when hovering over the main genre, the sub genre bar appears, to click on such subgenre)
> 5. custom tag sections collapse/expandle (to make room when u have large lists in multiple sections)
> 6. adding using + icon / enabling using checkbox (to make it more user-friendly to add/remove/change tag name)
> 7. when hovering over such tag, x icon appears to delete.
> 
> This way we solve most problems. What you guys think?

Great!
But is there a need for a mood line from above?

Maybe it's more convenient to choose the mood on the track card itself, as is now done with the rating?

**Comment by rshea0** [comment]
I like the mockups! Having tiered genres would be really nice as for some genres like house I have quite a lot of sub genres.

I think if the moods are going to be moved from the sidebar it would make more sense to have them on the bottom below genres to keep more information in the same place. With the current and proposed designs you need to click on three different sides of the screen to tag a track.

> What's your resolution btw?

3440x1440. Like I said I have a lot of genres :)

**Comment by bascurtiz** [comment]
@SunwalkerDJ 
The idea of Quick Tag is to be able to tag fast, so a direct approach preferred, by a 1-click or keyboard shortcut.
Hence the mood bar is needed. And it's not in the way imo.

Same principle applies to the stars/energy right now. Either 1-click to set or keyboard shortcut them, like `1`,`2`,`3`,`4`,`5`.
Same for all other custom characteristics.

And if you really need to make a custom note, like _"Marie's favorite B-day song!"_ or _"[mww] (mixes well with) Niggas in Paris"_,
u hit your preferred keyboard shortcut, like `Ctrl+N` or click the `Custom Note` button.

@rshea0 
Hmm, will play around with that idea of putting the moods on the bottom too.
I thought it would make sense to divide them in their own spot in the GUI, to make a distinction between them.
But your reasoning would be like it's more user-friendly when they are all closer to eachother right?

**Comment by rshea0** [comment]
> But your reasoning would be like it's more user-friendly when they are all closer to eachother right?

Exactly. It's going to take up the same amount of space regardless so it might as well be closer to the other tags. Maybe a small separator line could be added between the two if necessary.

**Comment by bascurtiz** [comment]
@rshea0 
Yep I'm getting to like the idea =)

Btw: I'm on 3440x1440 too.
Meaning you can approx. takes up 50 main genres, and per main genre, 50 sub genres.
Should be plenty lol.

**Comment by rosgr100** [comment]
Hi @bascurtiz, since you are talking about the GUI and the quick tag section, something that, to me at least, seems useful enough, is half star ratings.
It would be a welcome addition.

**Comment by bascurtiz** [comment]
@rosgr100 
Hmm, too niche imo. I've tried the Big 4 DJ apps + Mixxx & Engine DJ.
None of them are able to show half stars or set them.
What DJ app are you using?

**Comment by rosgr100** [comment]
Mostly Traktor [98% :-P], but i use Musicbee -which supports half stars- as my organizer and often enough as my library side by side with Traktor when i play.

It's something that people are requesting from NI since ages, but you know how it goes when it comes to NI. :-)

**Comment by Marekkon5** [comment]
In the latest commit, I've added subgenres - you can use that. You can also make a `Other` genre, which you'll never select and use it's subgenres as additional genres, since they are written to the same tag. You can get the binary in Actions tab. Let me know what you think, thanks
